# Generated by Django 3.2.5 on 2021-08-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savingsLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameonpassbook', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('accnumber', models.CharField(max_length=15)),
                ('mobnumber', models.CharField(max_length=10)),
            ],
        ),
    ]
