# Generated by Django 3.2.5 on 2021-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_oblogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmlogin',
            name='mobnum',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oblogin',
            name='mobnum',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
