# Generated by Django 3.2.5 on 2021-09-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210831_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('nameonpassbook', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('accnumber', models.CharField(max_length=15)),
                ('ATMnumber', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('mobnum', models.CharField(max_length=10)),
                ('adharcardimg', models.ImageField(upload_to='adhar_proof')),
                ('voteridimg', models.ImageField(upload_to='voterid_proof')),
                ('adharnum', models.CharField(max_length=15)),
                ('voteridnum', models.CharField(max_length=10)),
                ('accountbalance', models.IntegerField()),
                ('atmcard', models.BooleanField(default=False)),
                ('debitcard', models.BooleanField(default=False)),
            ],
        ),
    ]
