# Generated by Django 3.2.5 on 2021-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customer_details_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='ob_registered',
            field=models.BooleanField(default=False),
        ),
    ]
