# Generated by Django 3.2.5 on 2021-09-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_details_ob_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='accountbalance',
            field=models.CharField(max_length=10),
        ),
    ]
