# Generated by Django 3.2.9 on 2022-01-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customer_details_accountbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(max_length=100)),
                ('accountnum1', models.CharField(max_length=15)),
                ('person2', models.CharField(max_length=100)),
                ('accountnum2', models.CharField(max_length=15)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
    ]
