# Generated by Django 3.2.9 on 2022-01-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transactionhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
