# Generated by Django 3.2.9 on 2022-01-13 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='emailid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
