# Generated by Django 3.2.9 on 2022-01-20 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customer_details_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='bank_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
