# Generated by Django 3.2.9 on 2022-01-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220121_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='linkedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accnumber', models.CharField(max_length=100)),
                ('linkedaccnumber', models.CharField(max_length=100)),
                ('accounttype', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_ifsc_code', models.CharField(max_length=100)),
                ('bank_branch_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
