# Generated by Django 3.2.9 on 2022-01-22 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_linkedaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='bank_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
