# Generated by Django 3.2.9 on 2022-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_linkedaccounts_bank_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accnumber', models.CharField(max_length=100)),
                ('second_acc', models.CharField(max_length=100)),
                ('amounttransfered', models.CharField(max_length=100)),
                ('transactiontype', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
            ],
        ),
    ]
